### ISSUE TITLE
Adapt the documentation and update the deployment

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Demo-DatAgora-Deambulation-Bron#6]
- [x] Adapt [this documentation](https://github.com/VCityTeam/VCity-Deployments/blob/master/Metropole/DemoDatAgoraDeambulationBron.md) to [newly documented tag name policy](https://github.com/VCityTeam/UD-SV/tree/master/ImplementationKnowHow/ProjectOrganizationalLogic#concerning-docker)
 - [x] Upgrade the  [corresponding metropole instance](https://github.com/VCityTeam/VCity-Deployments/blob/master/Metropole/)
 - [x] Update the [VCity corporate website](https://gitlab.liris.cnrs.fr/VCityTeam/websites/-/blob/master/LirisProjet/content/demos/_index.md) with a pointer to this demo

**Comment by webanck** [comment]
@EricBoix : I updated the documentation to deploy the metropole instance, could you please try the upgrade?

**Comment by EricBoix** [comment]
@webanck Update on metropole instance ran smoothly. (BTW nice build and run shell script)
Yet, when you access the site the campus is not displayed which makes the situation a bit confusing.
The user needs to warp for the campus to appear.

**Comment by webanck** [comment]
@EricBoix The warp requirement was intended but it can be removed, see #1 for more on this.
