### ISSUE TITLE
Installation instructions seem to fail

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Demo-DatAgora-Deambulation-Bron#9]
Warning: this issue depends on [that issue resolution](https://github.com/VCityTeam/UD-Demo-DatAgora-Deambulation-Bron/issues/5).

If one follows the installation instructions of the `Reame.md`, and when running `npm install` one gets the following npm error message 
  `npm ERR! Could not install from "../UD-Viz" as it does not contain a package.json file.`

Indeed a manual installation of the ud-viz package seems implied by [this package.json dependency](https://github.com/VCityTeam/UD-Demo-DatAgora-Deambulation-Bron/blob/master/package.json#L20).

**Comment by webanck** [comment]
The specific UD-Viz package commitish has been specified in the `package.json` file (see the syntax [here](https://github.com/VCityTeam/UD-Demo-DatAgora-Deambulation-Bron/blob/72e6c0f4b1942b8ac7b38d5eda55888218fdaee1/package.json#L19)), which avoids any manual installation.
